# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Category title')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Tag title')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Video description')),
                ('published', models.DateTimeField(verbose_name='Video publication date')),
                ('title', models.CharField(max_length=100, verbose_name='Video title')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('video_id', models.CharField(max_length=500, unique=True, verbose_name='Youtube ID for video')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category', verbose_name='Video category')),
                ('tags', models.ManyToManyField(to='videos.Tag', verbose_name='Video tags')),
            ],
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date and time video views were counted')),
                ('views', models.BigIntegerField(verbose_name='Video view count')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Video', verbose_name='Video views are counted for')),
            ],
        ),
    ]
