# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=500, unique=True, verbose_name='Youtube ID for video'),
        ),
    ]
